spring.datasource.url=jdbc:mysql://localhost:3306/gigmate_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=nikunj@002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

gigmate.jwt.secret=9a4f2c8d3e1b7f6a0c5b4e3d2f1a6c7b8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b
gigmate.jwt.expiration=86400000
